var metaData = {
         "flw.registration.finalsilence" : "4000ms",
         "invalidInputDisconnectAudio" : "error.wrong.input.disconnect.wav",
         "maximumInvalidInputCount" : "2",
         "flw.registration.no.input.for.village" : "http://221.134.198.15/ananya/audio/flwRegistration/no.input.for.village.wav",
         "flw.registration.say.name" : "http://221.134.198.15/ananya/audio/flwRegistration/say.name.wav",
         "flw.registration.no.input.for.name" : "http://221.134.198.15/ananya/audio/flwRegistration/no.input.for.name.wav",
         "flw.registration.say.block" : "http://221.134.198.15/ananya/audio/flwRegistration/say.block.wav",
         "flw.registration.no.input.for.block" : "http://221.134.198.15/ananya/audio/flwRegistration/no.input.for.block.wav",
         "flw.registration.complete" : "http://221.134.198.15/ananya/audio/flwRegistration/registration.complete.wav",
         "flw.registration.confirm.recording" : "http://221.134.198.15/ananya/audio/flwRegistration/confirm.recording.wav",
         "flw.registration.record.audio.type" : "audio/x-wav",
         "maximumNoInputCount" : "2",
         "flw.registration.timeout" : "5s",
         "invalidInputRetryAudio" : "error.wrong.input.retry.wav",
         "flw.registration.dtmfterm" : "true",
         "flw.registration.say.village" : "http://221.134.198.15/ananya/audio/flwRegistration/say.village.wav",
         "flw.registration.welcome" : "http://221.134.198.15/ananya/audio/flwRegistration/welcome.wav",
         "flw.registration.submit.url" : "http://221.134.198.15/ananya/flw/register/",
         "flw.registration.max.record.time" : "10s",
         "audioFileBase" : "../audio/",
         "noInputDisconnectAudio" : "error.no.input.disconnect.wav",
         "noInputRetryAudio" : "error.no.input.retry.wav",
         "flw.registration.no.input.for.district" : "http://221.134.198.15/ananya/audio/flwRegistration/no.input.for.district.wav",
         "flw.registration.say.district" : "http://221.134.198.15/ananya/audio/flwRegistration/say.district.wav",
         "flw.registration.record.stop" : "#",
         "flw.registration.beep" : "true",
    };